//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtOrnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int Id { get; set; }
        public string urunAdi { get; set; }
        public Nullable<double> fiyat { get; set; }
        public string detay { get; set; }
        public Nullable<int> kategoriID { get; set; }
    }
}
